[project]
name = "french"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "googletrans==4.0.0rc1",
    "ipykernel>=6.29.5",
    "pydub>=0.25.1",
    "vosk>=0.3.45",
]
