[project]
name = "asyncio-http"
version = "0.1.0"
description = "Project to learn asynchronous handling of API requests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
