FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt -y upgrade
RUN apt-get install -y --no-install-recommends  \
    curl wget bash-completion sudo ca-certificates build-essential git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN echo 'alias ll="ls -l --color=auto"' >> /etc/bash.bashrc

SHELL [ "/bin/bash", "-c" ]

ARG USERNAME=seshu
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
    && chmod 440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
