FROM redhat/ubi8:latest

RUN dnf install -y sudo ncurses golang && dnf clean all
RUN useradd -m -s /bin/bash seshu \
    && echo "seshu ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/seshu \
    && chmod 0440 /etc/sudoers.d/seshu
    
RUN echo 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;10m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;14m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\\$ \[$(tput sgr0)\]"' >> /home/seshu/.bashrc && \
    echo 'alias ls="ls --color=auto"' >> /home/seshu/.bashrc && \
    echo 'alias ll="ls -l --color=auto"' >> /home/seshu/.bashrc && \
    echo 'export TERM=xterm-256color' >> /home/seshu/.bashrc

WORKDIR /app
USER seshu