[project]
name = "insta-automate"
version = "0.1.0"
description = "Instagram automation tools"
readme = "README.md"
authors = [
    { name = "SeshuTarapatla", email = "seshu.tarapatla@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.40",
]
